// Serbian core vocabulary for English speakers.
// To add or edit words, modify the entries below. Each entry:
//   { serbian: '...', english: '...', group: '...', marked: false }
// Save the file, then reload the page in your browser.

window.WORDS = [
    {"serbian": "biti", "english": "to be", "group": "Common verbs", "marked": false},
    {"serbian": "imati", "english": "to have", "group": "Common verbs", "marked": false},
    {"serbian": "ići", "english": "to go", "group": "Common verbs", "marked": false},
    {"serbian": "doći", "english": "to come", "group": "Common verbs", "marked": false},
    {"serbian": "znati", "english": "to know (a fact)", "group": "Common verbs", "marked": false},
    {"serbian": "poznavati", "english": "to know (a person)", "group": "Common verbs", "marked": false},
    {"serbian": "hteti", "english": "to want", "group": "Common verbs", "marked": false},
    {"serbian": "moći", "english": "to be able / can", "group": "Common verbs", "marked": false},
    {"serbian": "morati", "english": "to have to / must", "group": "Common verbs", "marked": false},
    {"serbian": "raditi", "english": "to work / to do", "group": "Common verbs", "marked": false},
    {"serbian": "jesti", "english": "to eat", "group": "Common verbs", "marked": false},
    {"serbian": "piti", "english": "to drink", "group": "Common verbs", "marked": false},
    {"serbian": "spavati", "english": "to sleep", "group": "Common verbs", "marked": false},
    {"serbian": "govoriti", "english": "to speak", "group": "Common verbs", "marked": false},
    {"serbian": "reći", "english": "to say", "group": "Common verbs", "marked": false},
    {"serbian": "čuti", "english": "to hear", "group": "Common verbs", "marked": false},
    {"serbian": "videti", "english": "to see", "group": "Common verbs", "marked": false},
    {"serbian": "gledati", "english": "to watch / to look", "group": "Common verbs", "marked": false},
    {"serbian": "dati", "english": "to give", "group": "Common verbs", "marked": false},
    {"serbian": "uzeti", "english": "to take", "group": "Common verbs", "marked": false},
    {"serbian": "pisati", "english": "to write", "group": "Common verbs", "marked": false},
    {"serbian": "čitati", "english": "to read", "group": "Common verbs", "marked": false},
    {"serbian": "kupovati", "english": "to buy", "group": "Common verbs", "marked": false},
    {"serbian": "plaćati", "english": "to pay", "group": "Common verbs", "marked": false},
    {"serbian": "voleti", "english": "to love / to like", "group": "Common verbs", "marked": false},
    {"serbian": "putovati", "english": "to travel", "group": "Common verbs", "marked": false},
    {"serbian": "početi", "english": "to start", "group": "Common verbs", "marked": false},
    {"serbian": "završiti", "english": "to finish", "group": "Common verbs", "marked": false},
    {"serbian": "naći", "english": "to find", "group": "Common verbs", "marked": false},
    {"serbian": "misliti", "english": "to think", "group": "Common verbs", "marked": false},
    {"serbian": "ja", "english": "I", "group": "Pronouns & basics", "marked": false},
    {"serbian": "ti", "english": "you (sg)", "group": "Pronouns & basics", "marked": false},
    {"serbian": "on", "english": "he", "group": "Pronouns & basics", "marked": false},
    {"serbian": "ona", "english": "she", "group": "Pronouns & basics", "marked": false},
    {"serbian": "ono", "english": "it", "group": "Pronouns & basics", "marked": false},
    {"serbian": "mi", "english": "we", "group": "Pronouns & basics", "marked": false},
    {"serbian": "vi", "english": "you (pl / formal)", "group": "Pronouns & basics", "marked": false},
    {"serbian": "oni", "english": "they (m)", "group": "Pronouns & basics", "marked": false},
    {"serbian": "one", "english": "they (f)", "group": "Pronouns & basics", "marked": false},
    {"serbian": "moj", "english": "my", "group": "Pronouns & basics", "marked": false},
    {"serbian": "tvoj", "english": "your (sg)", "group": "Pronouns & basics", "marked": false},
    {"serbian": "njegov", "english": "his", "group": "Pronouns & basics", "marked": false},
    {"serbian": "njen", "english": "her", "group": "Pronouns & basics", "marked": false},
    {"serbian": "naš", "english": "our", "group": "Pronouns & basics", "marked": false},
    {"serbian": "vaš", "english": "your (pl)", "group": "Pronouns & basics", "marked": false},
    {"serbian": "njihov", "english": "their", "group": "Pronouns & basics", "marked": false},
    {"serbian": "jedan", "english": "one", "group": "Numbers", "marked": false},
    {"serbian": "dva", "english": "two", "group": "Numbers", "marked": false},
    {"serbian": "tri", "english": "three", "group": "Numbers", "marked": false},
    {"serbian": "četiri", "english": "four", "group": "Numbers", "marked": false},
    {"serbian": "pet", "english": "five", "group": "Numbers", "marked": false},
    {"serbian": "šest", "english": "six", "group": "Numbers", "marked": false},
    {"serbian": "sedam", "english": "seven", "group": "Numbers", "marked": false},
    {"serbian": "osam", "english": "eight", "group": "Numbers", "marked": false},
    {"serbian": "devet", "english": "nine", "group": "Numbers", "marked": false},
    {"serbian": "deset", "english": "ten", "group": "Numbers", "marked": false},
    {"serbian": "jedanaest", "english": "eleven", "group": "Numbers", "marked": false},
    {"serbian": "dvanaest", "english": "twelve", "group": "Numbers", "marked": false},
    {"serbian": "petnaest", "english": "fifteen", "group": "Numbers", "marked": false},
    {"serbian": "dvadeset", "english": "twenty", "group": "Numbers", "marked": false},
    {"serbian": "trideset", "english": "thirty", "group": "Numbers", "marked": false},
    {"serbian": "pedeset", "english": "fifty", "group": "Numbers", "marked": false},
    {"serbian": "sto", "english": "hundred", "group": "Numbers", "marked": false},
    {"serbian": "hiljadu", "english": "thousand", "group": "Numbers", "marked": false},
    {"serbian": "pola", "english": "half", "group": "Numbers", "marked": false},
    {"serbian": "prvi", "english": "first", "group": "Numbers", "marked": false},
    {"serbian": "ponedeljak", "english": "Monday", "group": "Days & months", "marked": false},
    {"serbian": "utorak", "english": "Tuesday", "group": "Days & months", "marked": false},
    {"serbian": "sreda", "english": "Wednesday", "group": "Days & months", "marked": false},
    {"serbian": "četvrtak", "english": "Thursday", "group": "Days & months", "marked": false},
    {"serbian": "petak", "english": "Friday", "group": "Days & months", "marked": false},
    {"serbian": "subota", "english": "Saturday", "group": "Days & months", "marked": false},
    {"serbian": "nedelja", "english": "Sunday / week", "group": "Days & months", "marked": false},
    {"serbian": "januar", "english": "January", "group": "Days & months", "marked": false},
    {"serbian": "februar", "english": "February", "group": "Days & months", "marked": false},
    {"serbian": "mart", "english": "March", "group": "Days & months", "marked": false},
    {"serbian": "april", "english": "April", "group": "Days & months", "marked": false},
    {"serbian": "maj", "english": "May", "group": "Days & months", "marked": false},
    {"serbian": "jun", "english": "June", "group": "Days & months", "marked": false},
    {"serbian": "jul", "english": "July", "group": "Days & months", "marked": false},
    {"serbian": "avgust", "english": "August", "group": "Days & months", "marked": false},
    {"serbian": "septembar", "english": "September", "group": "Days & months", "marked": false},
    {"serbian": "oktobar", "english": "October", "group": "Days & months", "marked": false},
    {"serbian": "novembar", "english": "November", "group": "Days & months", "marked": false},
    {"serbian": "decembar", "english": "December", "group": "Days & months", "marked": false},
    {"serbian": "majka", "english": "mother", "group": "Family", "marked": false},
    {"serbian": "otac", "english": "father", "group": "Family", "marked": false},
    {"serbian": "brat", "english": "brother", "group": "Family", "marked": false},
    {"serbian": "sestra", "english": "sister", "group": "Family", "marked": false},
    {"serbian": "sin", "english": "son", "group": "Family", "marked": false},
    {"serbian": "ćerka", "english": "daughter", "group": "Family", "marked": false},
    {"serbian": "muž", "english": "husband", "group": "Family", "marked": false},
    {"serbian": "žena", "english": "wife / woman", "group": "Family", "marked": false},
    {"serbian": "deda", "english": "grandfather", "group": "Family", "marked": false},
    {"serbian": "baka", "english": "grandmother", "group": "Family", "marked": false},
    {"serbian": "ujak", "english": "uncle (mother's side)", "group": "Family", "marked": false},
    {"serbian": "stric", "english": "uncle (father's side)", "group": "Family", "marked": false},
    {"serbian": "tetka", "english": "aunt", "group": "Family", "marked": false},
    {"serbian": "dete", "english": "child", "group": "Family", "marked": false},
    {"serbian": "prijatelj", "english": "friend (m)", "group": "Family", "marked": false},
    {"serbian": "crven", "english": "red", "group": "Colors", "marked": false},
    {"serbian": "plav", "english": "blue", "group": "Colors", "marked": false},
    {"serbian": "žut", "english": "yellow", "group": "Colors", "marked": false},
    {"serbian": "zelen", "english": "green", "group": "Colors", "marked": false},
    {"serbian": "crn", "english": "black", "group": "Colors", "marked": false},
    {"serbian": "beo", "english": "white", "group": "Colors", "marked": false},
    {"serbian": "siv", "english": "gray", "group": "Colors", "marked": false},
    {"serbian": "roze", "english": "pink", "group": "Colors", "marked": false},
    {"serbian": "ljubičast", "english": "purple", "group": "Colors", "marked": false},
    {"serbian": "narandžast", "english": "orange", "group": "Colors", "marked": false},
    {"serbian": "braon", "english": "brown", "group": "Colors", "marked": false},
    {"serbian": "hleb", "english": "bread", "group": "Food & drink", "marked": false},
    {"serbian": "meso", "english": "meat", "group": "Food & drink", "marked": false},
    {"serbian": "riba", "english": "fish", "group": "Food & drink", "marked": false},
    {"serbian": "mleko", "english": "milk", "group": "Food & drink", "marked": false},
    {"serbian": "sir", "english": "cheese", "group": "Food & drink", "marked": false},
    {"serbian": "jaje", "english": "egg", "group": "Food & drink", "marked": false},
    {"serbian": "jabuka", "english": "apple", "group": "Food & drink", "marked": false},
    {"serbian": "banana", "english": "banana", "group": "Food & drink", "marked": false},
    {"serbian": "pomorandža", "english": "orange", "group": "Food & drink", "marked": false},
    {"serbian": "sok", "english": "juice", "group": "Food & drink", "marked": false},
    {"serbian": "voda", "english": "water", "group": "Food & drink", "marked": false},
    {"serbian": "kafa", "english": "coffee", "group": "Food & drink", "marked": false},
    {"serbian": "čaj", "english": "tea", "group": "Food & drink", "marked": false},
    {"serbian": "vino", "english": "wine", "group": "Food & drink", "marked": false},
    {"serbian": "pivo", "english": "beer", "group": "Food & drink", "marked": false},
    {"serbian": "supa", "english": "soup", "group": "Food & drink", "marked": false},
    {"serbian": "salata", "english": "salad", "group": "Food & drink", "marked": false},
    {"serbian": "pasta", "english": "pasta", "group": "Food & drink", "marked": false},
    {"serbian": "pirinač", "english": "rice", "group": "Food & drink", "marked": false},
    {"serbian": "krompir", "english": "potato", "group": "Food & drink", "marked": false},
    {"serbian": "paradajz", "english": "tomato", "group": "Food & drink", "marked": false},
    {"serbian": "luk", "english": "onion", "group": "Food & drink", "marked": false},
    {"serbian": "čokolada", "english": "chocolate", "group": "Food & drink", "marked": false},
    {"serbian": "sladoled", "english": "ice cream", "group": "Food & drink", "marked": false},
    {"serbian": "šećer", "english": "sugar", "group": "Food & drink", "marked": false},
    {"serbian": "so", "english": "salt", "group": "Food & drink", "marked": false},
    {"serbian": "kuća", "english": "house", "group": "Places", "marked": false},
    {"serbian": "stan", "english": "apartment", "group": "Places", "marked": false},
    {"serbian": "škola", "english": "school", "group": "Places", "marked": false},
    {"serbian": "prodavnica", "english": "shop", "group": "Places", "marked": false},
    {"serbian": "restoran", "english": "restaurant", "group": "Places", "marked": false},
    {"serbian": "kafić", "english": "café", "group": "Places", "marked": false},
    {"serbian": "hotel", "english": "hotel", "group": "Places", "marked": false},
    {"serbian": "grad", "english": "city", "group": "Places", "marked": false},
    {"serbian": "selo", "english": "village", "group": "Places", "marked": false},
    {"serbian": "zemlja", "english": "country / land", "group": "Places", "marked": false},
    {"serbian": "ulica", "english": "street", "group": "Places", "marked": false},
    {"serbian": "park", "english": "park", "group": "Places", "marked": false},
    {"serbian": "plaža", "english": "beach", "group": "Places", "marked": false},
    {"serbian": "planina", "english": "mountain", "group": "Places", "marked": false},
    {"serbian": "more", "english": "sea", "group": "Places", "marked": false},
    {"serbian": "reka", "english": "river", "group": "Places", "marked": false},
    {"serbian": "most", "english": "bridge", "group": "Places", "marked": false},
    {"serbian": "aerodrom", "english": "airport", "group": "Places", "marked": false},
    {"serbian": "bolnica", "english": "hospital", "group": "Places", "marked": false},
    {"serbian": "pijaca", "english": "market", "group": "Places", "marked": false},
    {"serbian": "crkva", "english": "church", "group": "Places", "marked": false},
    {"serbian": "banka", "english": "bank", "group": "Places", "marked": false},
    {"serbian": "dan", "english": "day", "group": "Time", "marked": false},
    {"serbian": "noć", "english": "night", "group": "Time", "marked": false},
    {"serbian": "jutro", "english": "morning", "group": "Time", "marked": false},
    {"serbian": "veče", "english": "evening", "group": "Time", "marked": false},
    {"serbian": "sat", "english": "hour / clock", "group": "Time", "marked": false},
    {"serbian": "minut", "english": "minute", "group": "Time", "marked": false},
    {"serbian": "vreme", "english": "time / weather", "group": "Time", "marked": false},
    {"serbian": "sada", "english": "now", "group": "Time", "marked": false},
    {"serbian": "danas", "english": "today", "group": "Time", "marked": false},
    {"serbian": "sutra", "english": "tomorrow", "group": "Time", "marked": false},
    {"serbian": "juče", "english": "yesterday", "group": "Time", "marked": false},
    {"serbian": "uvek", "english": "always", "group": "Time", "marked": false},
    {"serbian": "nikad", "english": "never", "group": "Time", "marked": false},
    {"serbian": "ponekad", "english": "sometimes", "group": "Time", "marked": false},
    {"serbian": "često", "english": "often", "group": "Time", "marked": false},
    {"serbian": "odmah", "english": "immediately", "group": "Time", "marked": false},
    {"serbian": "dobar", "english": "good", "group": "Adjectives", "marked": false},
    {"serbian": "loš", "english": "bad", "group": "Adjectives", "marked": false},
    {"serbian": "veliki", "english": "big", "group": "Adjectives", "marked": false},
    {"serbian": "mali", "english": "small", "group": "Adjectives", "marked": false},
    {"serbian": "star", "english": "old", "group": "Adjectives", "marked": false},
    {"serbian": "mlad", "english": "young", "group": "Adjectives", "marked": false},
    {"serbian": "nov", "english": "new", "group": "Adjectives", "marked": false},
    {"serbian": "lep", "english": "beautiful / nice", "group": "Adjectives", "marked": false},
    {"serbian": "ružan", "english": "ugly", "group": "Adjectives", "marked": false},
    {"serbian": "brz", "english": "fast", "group": "Adjectives", "marked": false},
    {"serbian": "spor", "english": "slow", "group": "Adjectives", "marked": false},
    {"serbian": "jak", "english": "strong", "group": "Adjectives", "marked": false},
    {"serbian": "slab", "english": "weak", "group": "Adjectives", "marked": false},
    {"serbian": "topao", "english": "warm", "group": "Adjectives", "marked": false},
    {"serbian": "hladan", "english": "cold", "group": "Adjectives", "marked": false},
    {"serbian": "vruć", "english": "hot", "group": "Adjectives", "marked": false},
    {"serbian": "sladak", "english": "sweet", "group": "Adjectives", "marked": false},
    {"serbian": "gorak", "english": "bitter", "group": "Adjectives", "marked": false},
    {"serbian": "srećan", "english": "happy", "group": "Adjectives", "marked": false},
    {"serbian": "tužan", "english": "sad", "group": "Adjectives", "marked": false},
    {"serbian": "umoran", "english": "tired", "group": "Adjectives", "marked": false},
    {"serbian": "gladan", "english": "hungry", "group": "Adjectives", "marked": false},
    {"serbian": "žedan", "english": "thirsty", "group": "Adjectives", "marked": false},
    {"serbian": "težak", "english": "difficult / heavy", "group": "Adjectives", "marked": false},
    {"serbian": "lak", "english": "easy / light", "group": "Adjectives", "marked": false},
    {"serbian": "čist", "english": "clean", "group": "Adjectives", "marked": false},
    {"serbian": "prljav", "english": "dirty", "group": "Adjectives", "marked": false},
    {"serbian": "pun", "english": "full", "group": "Adjectives", "marked": false},
    {"serbian": "prazan", "english": "empty", "group": "Adjectives", "marked": false},
    {"serbian": "otvoren", "english": "open", "group": "Adjectives", "marked": false},
    {"serbian": "zatvoren", "english": "closed", "group": "Adjectives", "marked": false},
    {"serbian": "glava", "english": "head", "group": "Body", "marked": false},
    {"serbian": "ruka", "english": "hand / arm", "group": "Body", "marked": false},
    {"serbian": "noga", "english": "leg / foot", "group": "Body", "marked": false},
    {"serbian": "oko", "english": "eye", "group": "Body", "marked": false},
    {"serbian": "uho", "english": "ear", "group": "Body", "marked": false},
    {"serbian": "usta", "english": "mouth", "group": "Body", "marked": false},
    {"serbian": "nos", "english": "nose", "group": "Body", "marked": false},
    {"serbian": "kosa", "english": "hair", "group": "Body", "marked": false},
    {"serbian": "srce", "english": "heart", "group": "Body", "marked": false},
    {"serbian": "stomak", "english": "stomach", "group": "Body", "marked": false},
    {"serbian": "zub", "english": "tooth", "group": "Body", "marked": false},
    {"serbian": "prst", "english": "finger", "group": "Body", "marked": false},
    {"serbian": "leđa", "english": "back", "group": "Body", "marked": false},
    {"serbian": "lice", "english": "face", "group": "Body", "marked": false},
    {"serbian": "sunce", "english": "sun", "group": "Weather & nature", "marked": false},
    {"serbian": "kiša", "english": "rain", "group": "Weather & nature", "marked": false},
    {"serbian": "sneg", "english": "snow", "group": "Weather & nature", "marked": false},
    {"serbian": "oblak", "english": "cloud", "group": "Weather & nature", "marked": false},
    {"serbian": "vetar", "english": "wind", "group": "Weather & nature", "marked": false},
    {"serbian": "nebo", "english": "sky", "group": "Weather & nature", "marked": false},
    {"serbian": "drvo", "english": "tree", "group": "Weather & nature", "marked": false},
    {"serbian": "cvet", "english": "flower", "group": "Weather & nature", "marked": false},
    {"serbian": "životinja", "english": "animal", "group": "Weather & nature", "marked": false},
    {"serbian": "pas", "english": "dog", "group": "Weather & nature", "marked": false},
    {"serbian": "mačka", "english": "cat", "group": "Weather & nature", "marked": false},
    {"serbian": "ptica", "english": "bird", "group": "Weather & nature", "marked": false},
    {"serbian": "zdravo", "english": "hello", "group": "Common phrases", "marked": false},
    {"serbian": "ćao", "english": "hi / bye", "group": "Common phrases", "marked": false},
    {"serbian": "hvala", "english": "thank you", "group": "Common phrases", "marked": false},
    {"serbian": "molim", "english": "please / you're welcome", "group": "Common phrases", "marked": false},
    {"serbian": "izvini", "english": "sorry / excuse me", "group": "Common phrases", "marked": false},
    {"serbian": "da", "english": "yes", "group": "Common phrases", "marked": false},
    {"serbian": "ne", "english": "no", "group": "Common phrases", "marked": false},
    {"serbian": "dobro jutro", "english": "good morning", "group": "Common phrases", "marked": false},
    {"serbian": "dobar dan", "english": "good day", "group": "Common phrases", "marked": false},
    {"serbian": "laku noć", "english": "good night", "group": "Common phrases", "marked": false},
    {"serbian": "doviđenja", "english": "goodbye", "group": "Common phrases", "marked": false},
    {"serbian": "kako si", "english": "how are you (sg)", "group": "Common phrases", "marked": false},
    {"serbian": "kako ste", "english": "how are you (pl/formal)", "group": "Common phrases", "marked": false},
    {"serbian": "dobrodošao", "english": "welcome (to a man)", "group": "Common phrases", "marked": false},
    {"serbian": "dobrodošla", "english": "welcome (to a woman)", "group": "Common phrases", "marked": false},
];
